### ISSUE TITLE
[Bug]: Source control enabled in first connection

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-vscode-web#41]
### Function app name

glengatest-flex-py

### Expected Behavior *

+ Source control should be disabled in the web version, since it's not hooked up to any repos.
+ I should be asked to connect a GH repo.

### Actual Behavior *

When I commit the files in the window and click **Commit** I get this error:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b3d5e578-1e33-4b64-8a8e-8f43b87f6278">

>[!NOTE]  
>On full refresh, I longer had a GitHub repo detected.

### Steps to Reproduce

1. Create code project
2. Select the source control button
3. Stage the new files and click **Commit**

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
There unfortunately isn't a mechanism in VS Code to warn users when they click on this workbench SCM view (or any particular built-in view). To be more clear - the Outline and Timeline views have been removed on launch to make the Workspace Tree View more clear. This will make the git interaction more clear to specify the email and username

The walkthrough can also supply this too. We don't want to completely hide the SCM view even if their credentials are not set - because this can be confusing as there is nothing limiting them from doing git config themselves

Also, this error message is correct/intended as it does recommend to do git config as it is required before doing commits
