### ISSUE TITLE
[Bug]: Walkthrough should be contributed the normal way

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-vscode-web#49]
### Expected Behavior *

The Azure Functions Walkthrough shows up in the place it should, which is in the `Open Walkthrough` quick pick:
<img width="636" alt="image" src="https://github.com/user-attachments/assets/ad665492-cae7-4ea3-a425-115e0cbfca97">

which would also allow it to be shown here on the Welcome page:
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/72f778ab-12be-4353-9701-ddfa3f59f1ca">

### Actual Behavior *

There's a separate command to open the Azure Functions walkthrough

<img width="645" alt="image" src="https://github.com/user-attachments/assets/c2bdc950-e86e-4fa3-bfab-ebc847ac2c06">

### Priority

Low (happening rarely)

**Comment by bamurtaugh** [comment]
Believe this is part of https://github.com/Azure/azure-functions-vscode-web/issues/38 and reaffirms it's important for the walkthrough to appear in the typical VS Code way, rather than a separate menu @EvanR-Dev (as mentioned in https://github.com/Azure/azure-functions-vscode-web/issues/38#issuecomment-2297305933)

**Comment by EvanR-Dev** [comment]
Interesting - the regular Azure Functions ext does not do this. I have updated our ext to now be under walkthroughs and no longer a separate cmd
