### ISSUE TITLE
[Bug]: Report an issue URL needs fixing

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-vscode-web#56]
### Actual Behavior *

<img width="931" alt="image" src="https://github.com/user-attachments/assets/e9d8fcc1-34b7-4aed-86e3-19cf935f378f">
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/4bc8e7ed-8860-4754-bdab-bbd4bdcc0c35">

### Priority

Low (happening rarely)

**Comment by EvanR-Dev** [comment]
The report an issue button that appears here is emitted from the vscode-azuretools extension SDK (because each command is registered under this SDK, so error handling like this is present). The issue here is it will use a "bugs" GitHub URL specified in package.json, but "/new" automatically will be appended to it no matter what: https://github.com/microsoft/vscode-azuretools/blob/56a0d82e4ffa0a75a5fe4ae2035d92b84ba0f7f6/utils/src/reportAnIssue.ts#L84C5-L85C67

As a result, this forces a GitHub login to file an issue, which reduces the problem down to #54. We cannot change this - so this report an issue button has been removed from these error boxes. We also already have a Give feedback button in the wrapper that will just lead to the issues page
